### ISSUE TITLE
Redirect instead of download, unexpected download file name

### ISSUE THREAD

**Issue by d10r** [Kagee/audible-downloader#3]
When running on Ubuntu 14.04 for audible.de, I had 2 issues:
* With the user agent set (Win, Trident), Audible redirects to a page advertising a download application instead of actually downloading.
* The filename of the download for me isn't *admhelper* as expected by the script, thus it fails.

I created a fork with changed user agent and *blind downloading*: it just clicks the download button and waits for 60 seconds before clicking the next one. This works for me, however the script doesn't know if the download actually succeeds. Also, the 60 seconds may not be enough if the lib contains huge audiobooks. See [commit](https://github.com/d10r/audible-downloader/commit/75f27b319906317e6c0ee8c67ae48f336dae9684).

**Comment by Kagee** [comment]
The code still appears to work with audible.com as intended, so i'm not willing to look into this to closely.

A couple of comments: 
We use the user-agent because audible gives some browsers (i.e. IE11) files that will open in Audible Download Helper instead of downloading the file via the browser. Audible Download Helper will then take care of the download. 

We use this trick so we get the admhelper-file, with we can use to download the file using python, not chrome. This gives us more control of the download.

On audible.com, pressing the download button in this scenario will only download the admhelper file, and not redirect the user away from the library page. If you can get the code/broser/website to only download admhelper (or whatever the file might be called on audible.de), it should be possible to adapt the code. Checking how audible.de works in a real IE 11 might help with this.

**Comment by d10r** [comment]
Ah, so this is intended behaviour?
And since IE is mentioned, I guess it's meant to be run on Windows? I wasn't aware of this.

**Comment by Kagee** [comment]
The download of admhelper is intended, yes. The code was written on and I run it on Linux. The reason the selenium chromedriver is instructed to use a IE user-agent is because this triggers audible.com to serve links to admhelper files instead of direct downloads.

**Comment by d10r** [comment]
I see. Doesn't seem to work on audible.de then.
That's where I end up: [screenshot](https://ipfs.io/ipfs/QmXqwwjNmiRPy4v2yh48jcY9cAcNwcvC2w17Jrvv5QXE4W)

**Comment by Kagee** [comment]
Please see the new instructions in the README, they should allow you to use the code w/o modifications. Turn out it was easy to make an account on .de to test.

**Comment by d10r** [comment]
Thx!
